### ISSUE TITLE
Python3 compatibility

### ISSUE THREAD

**Issue by stephane-caron** [haudren/stabilipy#3]
Installing the library with `pip3` on my system raises errors as print messages in `stabilipy/backends.py` use the old syntax:
```
$ pip3 install . --user --upgrade
Unpacking /home/tastalian/Software/stabilipy
  Running setup.py (path:/tmp/pip-ktd8ph_9-build/setup.py) egg_info for package from file:///home/tastalian/Software/stabilipy
Installing collected packages: StabiliPy
  Found existing installation: StabiliPy 0.1.0
    Can't uninstall 'StabiliPy'. No files were found to uninstall.
  Running setup.py install for StabiliPy
      File "/home/tastalian/.local/lib/python3.4/site-packages/stabilipy/backends.py", line 53
        print "Error :( "
                        ^
    SyntaxError: invalid syntax
    
  Could not find .egg-info directory in install record for StabiliPy==0.1.0 from file:///home/tastalian/Software/stabilipy in /home/tastalian/.local/lib/python3.4/site-packages
```

**Comment by haudren** [comment]
Yes you are right, I tried to use python3 a while ago, but encountered some problems (could not make it run with both 2 and 3). Maybe it's time to give it another go, or at least upload a python3 branch.

**Comment by haudren** [comment]
Ok the python3 support is ready on the branch `topic/python3`. You can give it a go, I will merge soon :smile_cat: 

Note that you might need to:
- Update `pyparma` to `0.5.0`
- Install `future`
